# Fly.io configuration for Digital Cookbook
# Runs both frontend (Nginx) and backend (Express) in a single container

app = "recipebook-4i0q-w"  # Update this to match your actual Fly.io app name
primary_region = "sea" 
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  # Explicitly specify the Dockerfile to use
  dockerfile = "Dockerfile.fly"
  
  [build.args]
    NODE_ENV = "production"

[env]
  NODE_ENV = "production"
  PORT = "5000"

# HTTP service configuration
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Health check configuration
  [[http_service.checks]]
    interval = "30s"           # Check every 30s (reduced frequency saves resources)
    timeout = "5s"             # 5s timeout (generous for cold starts)
    grace_period = "10s"       # 10s grace period for startup
    method = "GET"
    path = "/"

# VM configuration (free tier: shared-cpu-1x with 256MB)
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

